name: prompt-pilot

services:
  backend:
    build: 
      context: ./backend  
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_network


networks: 
  app_network: